### ISSUE TITLE
pages not getting 

### ISSUE THREAD

**Issue by Balu2311** [whoiskatrin/financial-statement-pdf-extractor#3]
cmd = "pdfgrep -Pn '^(?s:(?=.*Revenue)|(?=.*Income))' " + pdf + " | awk -F\":\" '$0~\":\"{print $1}' | tr '\n' ','"
            pages = subprocess.check_output(cmd, shell=True).decode("utf-8")

**Comment by whoiskatrin** [comment]
you would need modify the query, I would assume the format of your document might be different
